### PR TITLE
Fixed issue with third-party comments for a cooperation #43

### LINKED ISSUE #43: [Comments] Any user can create and get comments for a cooperation they are not involved in
**Description:** Any user can create and get comments for a cooperation they are not involved in

**Reproducible:** always.

**Preconditions:**
The user is logged in.

**Steps to reproduce:**
1. Create a comment for a cooperation current user not involved in (niether initiator nor receiver).

**Actual result:**
The comment is created.

**Expected result:**
A forbidden error must appear.

### PR DESCRIPTION
**Pull request by Olenka-Hryk**
Resolved unauthorized access to comments for uninvolved users in cooperations: Close #43

Previously, when one user created a cooperation and created a comment on it:
screen 1
_any user not involved_ (neither as initiator nor receiver) _could create and access comments on a cooperation_ initiated by another user: 
screen 2

Now, **users not involved (neither as initiator nor receiver)** now receive a **Forbidden error** when attempting to access comments for cooperations initiated by other users: 
Screenshot 2024-04-28 at 15 48 47
and receive a **Forbidden error** when attempting to create comments for cooperations initiated by other users:
Screenshot 2024-04-28 at 15 53 41

### CODE REVIEW

**Review by m6xcom — APPROVED** [review]

**Review by docia — APPROVED** [review]

File: src/services/comment.js [hunk 1]
```diff
@@ -1,13 +1,25 @@
 const Comment = require('~/models/comment')
+const Cooperation = require('~/models/cooperation')
+const { createForbiddenError } = require('~/utils/errorsHelper')
 
 const commentService = {
   addComment: async (data) => {
     const { text, author, authorRole, cooperationId } = data
 
+    const { initiator, receiver } = await Cooperation.findById(cooperationId)
```
Comment (vlad-khrychov) [inline src/services/comment.js:9]: What happens if a client provides non-existent `cooperationId`? Has it been checked before?

Comment (Olenka-Hryk) [reply src/services/comment.js:9]: When a client provides **a non-existent** ```cooperationId``` to create a new comment on this cooperation (using the _POST method_), they receive the following error:
Screenshot 2024-04-30 at 14 47 39
Also, when a client provides **a non-valid format** for ```cooperationId```, they receive the following error:
Screenshot 2024-04-30 at 14 46 22
The same situation occurs when attempting to get a comment on **a non-existent** or **improperly formatted** ```cooperationId``` (using the GET method).

_These errors are handled by the following middleware:_
Screenshot 2024-04-30 at 14 58 22

Comment (vlad-khrychov) [reply src/services/comment.js:9]: Thanks a lot!

**Review by vlad-khrychov — APPROVED** [review]
